### ISSUE TITLE
corrupted palette

### ISSUE THREAD

**Issue by Het-AbobaMuhmuh** [justin3009/MMX3-ZeroProject#12]
neon tiger's palette gets corrupted after you hit him with the z saber
![cfa7a0e8-4c77-4a08-b3b9-191f6d678411](https://user-images.githubusercontent.com/112741571/197024544-006fc82c-b62e-4c2b-9502-4dc9440fa7a0.png)

**Comment by delta7890** [comment]
Can confirm.  Occurs with both X and Zero's Z Sabers, but only in Neon Tiger's stage.  The issue does not occur in the Doppler stage rematch.

**Comment by justin3009** [comment]
I can't reproduce this. I HAVE seen it before but I have never been able to reproduce it. Whether it's at full life, after he uses his special, anything. It just doesn't trigger for me.

**Comment by delta7890** [comment]
More specifically if this helps with your testing, it's the "swirling" effect produced by the Z Saber wave after it connects with Neon Tiger that triggers the palette corruption.  A normal Z Saber attack without the blade wave doesn't cause this issue.

![Mega Man X3 - Zero Project v4 5002](https://user-images.githubusercontent.com/34465681/217364534-0b216a8c-8436-461a-b7de-16ee355c6117.png)

Could it be related to the very similar bug (which you fixed!) that I encountered with Mad Joey some time ago?

**Comment by justin3009** [comment]
It very well could be and that's what's bugging me. I can't reproduce it no matter what I do so I'm not entirely sure why this would happen. Did you die at all and then fight him or was it just a flat go into the level and beat him? The thing that gets me is the palette MUST'VE been overwritten by something but there shouldn't be anything that touches that palette swatch since legit every single enemy in the game uses it.

**Comment by delta7890** [comment]
After some further testing, I can confirm that if you die at any point during Neon Tiger's stage, the palette bug does not occur.  You need to get through in a single go.

**Comment by delta7890** [comment]
After some further testing, I've confirmed that if you die after the halfway point of the stage, the palette bug does not occur.  I wonder if it has something to do with the mid-stage boss.  If you die in the beginning of the stage and run through to the end without any additional deaths, the bug still occurs.

**Comment by justin3009** [comment]
Was able to reproduce it now! I have two separate save states to track the difference. What seems to be issue is the palette it sets AFTER the saber wave is done. It should be "29" but it's setting itself to "2D" for some reason. I actually don't have any idea _why_ that would be but I'm going to look into it more. This is a very specific and odd bug.

**Comment by delta7890** [comment]
Glad you were able to reproduce it!

**Comment by justin3009** [comment]
I think I might've fixed it now. It's pretty jank but it should hopefully work.

When you hit the boss door for Neon Tiger, it'll specifically check if you're on his level and then also specifically check if you've hit the second checkpoint (IE: The boss hallway). If so, it'll set the value properly so it doesn't do that weird issue. I'll update the github files now.

**Comment by delta7890** [comment]
Can confirm this is fixed!  Neon Tiger no longer suffers from the palette bug as he did before!
