### ISSUE TITLE
X - no damage upgrade from upgrade/chip

### ISSUE THREAD

**Issue by bakefrey** [justin3009/MMX3-ZeroProject#16]
Someone else posted this on forum;

> Justin3009 the game has an error for handling X's defense, X doesn't gain defense until he get golden armour (armour part doesn't give defense, armour chip doesn't give it either), it behaves like this since 4.0.

**Comment by justin3009** [comment]
Confirmed bug that is now fixed. I, somehow, deleted some code and forgot to have it branch properly so it never loaded the armor check.

Source version is now fixed.

**Comment by justin3009** [comment]
Also, for your post before it was edited or whichever it was:

>  Hey everyone, I waey everyone, I wanted to ask something. How hard would it be to make a save hack for vanilla X3 based on the saving system from this project (with the save/load menu and everything) ? I saw that the project is now open source on github and I thought about trying to fiddle with it myself, but I'm not sure what to look for (also I'm not very experienced).

There's a section in the "MMX3_OriginalLocations.asm" code labeled as:

"; Setting up Save/Load Screen (SRAM starts at $70:0000 - $70:0100 for basis though)"

This pretty much draws the entirety of the save screen. You'd then have to likely follow those into the "MMX3_NewCode_Locations.asm". It's a lot.

**Comment by bakefrey** [comment]
Thanks. That was a weird edit, I actually copied and pasted the bug report
from another forum, as someone recommended the OP report the bug on the
GitHub page but they never did, and when I copied the post the first time,
I copied the wrong one.

I'll try and find that post again and cite your reply to them in case
they're still interested.
