### ISSUE TITLE
"No" text on Save/Load this File not aligned with cursor arrow. v4.2/v4.3

### ISSUE THREAD

**Issue by delta7890** [justin3009/MMX3-ZeroProject#6]
![Mega Man X3 - Zero Project v4 3000](https://user-images.githubusercontent.com/34465681/94344724-3cc48480-ffef-11ea-84d3-7ca523f3667c.png)

In previous builds the word "No" was positioned immediately to the right of the cursor arrow seen in this image.  "No" is now positioned further to the left, but the cursor arrow's position has not been altered to compensate for this change.

This does not impact the actual saving and loading of files.

**Comment by justin3009** [comment]
Fixed!

```
		LDA $05 ;Loads $7E:0005 (Temp. storage for cursor X coordinate)
		CLC
		ADC #$48 ;Adds #$48 to current value.
		STA $05 ;Stores to $7E:0005 (Temp. storage for cursor X coordinate)
```

Just had to alter this to:

```
		LDA $05 ;Loads $7E:0005 (Temp. storage for cursor X coordinate)
		CLC
		ADC #$28 ;Adds #$28 to current value.
		STA $05 ;Stores to $7E:0005 (Temp. storage for cursor X coordinate)
```
