### ISSUE TITLE
Ride Armors falling into pits crash the game.

### ISSUE THREAD

**Issue by SabinStargem** [justin3009/MMX3-ZeroProject#8]
Playing as X during the Volt Crawfish stage, I fell into a pit while riding the "H" armor.  The game glitched out, making weird sounds and artifacts.  The emulator in use was Bizhawk with the Mednafan Faust core.

**Comment by justin3009** [comment]
Unable to reproduce, also the first time I've heard of this happening. Possibly an emulation issue?

**Comment by SabinStargem** [comment]
It isn't a concern anymore, we now have BSNES manifest files to make it compatible with Zero Project.  :)

**Comment by TallgeeseHeaven** [comment]
Sorry to dig this up, but I am able to trigger this on RetroArch's bsnes and bsnes-jg core, the latter of which is supposed to be cycle-accurate. I am able to do it by jumping into the first water pit in Toxic Seahorse's stage with the Frog Ride Armor.

It does not quite crash, however; just heavily corrupts the graphics.
